SConscriptChdir(0)

import os

def RBConfig(param):
	return os.popen('ruby -e"require \'rbconfig\'; print Config::CONFIG[\'' + param + '\']"').read()


env = Environment(
	# GCC flags for building libchipmunk
	CCFLAGS = RBConfig('CFLAGS').split() + ['-O3', '-ffast-math', '-std=gnu99'],
	CPPPATH = ['../src', '../src/constraints', RBConfig('topdir')],
)

# OSX UB flags
SDK = "/Developer/SDKs/MacOSX10.4u.sdk"
env.Append(
	CCFLAGS = ['-arch', 'ppc', '-arch', 'i386', '-isysroot', SDK],
	LINKFLAGS = ['-arch', 'ppc', '-arch', 'i386', '-isysroot', SDK, '-Wl,-syslibroot,' + SDK, '-mmacosx-version-min=10.4'],
)

src = [
	Glob('ext/*.c'),
]

ext = env.LoadableModule(
	'chipmunk.bundle', 
	src,
	LIBS=['chipmunk', RBConfig('LIBRUBYARG_SHARED')],
	LIBPATH='..',
)

docs = env.Command(
	target = 'doc/',
	source = 'doc_dummy.rb',
	action = 'cd ruby; rdoc doc_dummy.rb',
)

Alias('.', [ext])
