import os

def RBConfig(param):
	return os.popen('ruby -e"require \'rbconfig\'; print Config::CONFIG[\'' + param + '\']"').read()

#print RBConfig('CFLAGS')

env = Environment(
	# GCC flags for building libchipmunk
	CCFLAGS = RBConfig('CFLAGS').split() + ['-O3', '-ffast-math', '-std=gnu99'],
	CPPPATH = ['../../src', '../../src/constraints', RBConfig('topdir')],
)

src = [
	Glob('*.c'),
]

ext = env.LoadableModule(
	'../chipmunk.bundle', 
	src,
	LIBS=['chipmunk', RBConfig('LIBRUBYARG_SHARED')],
	LIBPATH='../..',
)

docs = Command(
	target = '../doc/',
	source = '../doc_dummy.rb',
	action = 'cd ruby; rdoc doc_dummy.rb',
)

Alias('..', [ext, docs])
