env = Environment(
	# GCC flags for building libchipmunk
	CCFLAGS = ['-std=gnu99', '-O3', '-ffast-math'],
)

# OSX UB flags
env.Append(CCFLAGS = ['-arch', 'ppc', '-arch', 'i386'])

src = [
	Glob('*.c'),
	Glob('constraints/*.c'),
]

env.StaticLibrary(
	'../chipmunk', 
	src,
)
